### ISSUE TITLE
Open3D problem

### ISSUE THREAD

**Issue by PetrusCrus** [anthonyzhou-1/ldm_pdes#2]
Hello, when running `python validate_ldm.py --config=configs/cylinder/ldm/FF/ldm_DiT_FF.yaml` I encountered the following error:
```
Traceback (most recent call last):
  File "/mnt/data/ldm_pdes/validate_ldm.py", line 434, in <module>
    main(args)
  File "/mnt/data/ldm_pdes/validate_ldm.py", line 419, in main
    validate_cylinder(config, device)
  File "/mnt/data/ldm_pdes/validate_ldm.py", line 70, in validate_cylinder
    log = pl_module.log_images(batch, plot_diffusion_rows=False, plot_denoise_rows=False)
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/ldm_pdes/modules/models/ddpm.py", line 957, in log_images
    z, c, x, xrec, xc = self.get_input(batch, 
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/ldm_pdes/modules/models/ddpm.py", line 582, in get_input
    c = self.get_learned_conditioning(xc)
  File "/mnt/data/ldm_pdes/modules/models/ddpm.py", line 533, in get_learned_conditioning
    c = self.cond_stage_model(x, pos, self.cond_stage_model.latent_grid, pad_mask)
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/ldm_pdes/modules/models/ae/gino_ae.py", line 531, in forward
    z = self.encoder(x, input_geom, latent_queries, pad_mask) # b c n1 n2 n3
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/ldm_pdes/modules/models/ae/gino_ae.py", line 361, in forward
    latent = self.gino_encoder(x, input_geom, latent_queries) # shape [batch, n_gridpts_1, ..., n_gridpts_n, f_dim]
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/ldm_pdes/modules/models/ae/gino_ae.py", line 113, in forward
    spatial_nbrs = self.nb_search_out(input_geom, 
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/ldm_pdes/modules/modules/neighbor_search.py", line 65, in forward
    search_return = self.search_fn(data, queries, radius)
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/open3d/ml/torch/python/layers/neighbor_search.py", line 126, in forward
    table = ops.build_spatial_hash_table(
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/open3d/ml/torch/python/ops.py", line 1184, in build_spatial_hash_table
    *_torch.ops.open3d.build_spatial_hash_table(
  File "/mnt/data/miniconda3/envs/ldm-open3d/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: invalid shape for 'points', got [2060, 2], expected [num_points(2060), 3]
```
From Open3D's FixedRadiusSearch.forward I found:
> Arguments:
>   points: The 3D positions of the input points. It can be a RaggedTensor.

It seems that it can only handle 3D coordinates (correct me if I'm wrong). But when using first-frame conditioning, ddpm.py indirectly invokes FixedRadiusSearch to process first frame data (which is 2D), causing this problem. Is it because I misconfigured something or ldm_DiT_FF just can't be ran with Open3D enabled?

**Comment by anthonyzhou-1** [comment]
Hi! Thank you for reaching out. You are correct that open3D requires 3-dimensional positional coordinates, however in the config file in the repo ([configs/cylinder/ldm/FF/ldm_DiT_FF.yaml](https://github.com/anthonyzhou-1/ldm_pdes/blob/main/configs/cylinder/ldm/FF/ldm_DiT_FF.yaml)) the option for using open3D is turned off for the conditional encoder ([Line 165](https://github.com/anthonyzhou-1/ldm_pdes/blob/8b22e1b9061184628c3f1d4c433488721a80b1bc/configs/cylinder/ldm/FF/ldm_DiT_FF.yaml#L165)). I'm not able to reproduce this error on my end, so I'm not sure if your implementation is somehow defaulting to using open3D (which is the default option if the flag is not set to false). Best of luck and let me know if there are any more concerns!
